### ISSUE TITLE
Decoratives & Color selection

### ISSUE THREAD

**Issue by Peabrained** [nickcool9999/Productive-Industries#7]
When an item has customizable color (e.g. pillars, paths, ramps), you can click on the color box to open up all the color choices. This gui that displays all the color choices fails to open up upon clicking the color box.

**Comment by nickcool9999** [comment]
i will look into it. thanks.

**Comment by nickcool9999** [comment]
I will just add that I am going to also at the same time when fixing this create a controller-supported options menu so people can use these features on Xbox.

**Comment by nickcool9999** [comment]
fixed in new version
