### ISSUE TITLE
Can't load or create saves

### ISSUE THREAD

**Issue by JD760** [nickcool9999/Productive-Industries#9]
Can't select the 'choose file' option, and when pressing play, the screen gets stuck before loading assets. Not sure if this affects any others. When i press play, the screen will go black as if it is about to load assets, but nothing is there. I can still enter the ROBLOX menu and reset/ leave through that, so this is a game problem. Still not sure why this has happened.

**Comment by JD760** [comment]
EDIT: tried playing the game with another account, and had the same issue

**Comment by nickcool9999** [comment]
This has been fixed.
